language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t truongnguyen/docker-prod-grade -f Dockerfile.dev .

script:
  - docker run -e CI=true truongnguyen/docker-prod-grade npm run test 
